-- AlterTable
ALTER TABLE `activityevent` MODIFY `type` ENUM('ITEM_ADDED', 'ITEM_DELETED', 'ITEM_UPDATED', 'ITEM_USED', 'ITEM_PURCHASED', 'ITEM_VIEWED', 'WAREHOUSE_ADDED', 'WAREHOUSE_DELETED', 'WAREHOUSE_UPDATED', 'REMINDER_TRIGGERED', 'ITEM_EXPIRING', 'ITEM_LOW_STOCK') NOT NULL;

-- AlterTable
ALTER TABLE `item` ADD COLUMN `quantityUnit` VARCHAR(191) NULL;

-- AlterTable
ALTER TABLE `warehouse` ADD COLUMN `hideDetailsButton` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `hideQuantity` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `hideQuantitySlider` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `hideUseButton` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `itemsSuffix` VARCHAR(191) NULL;
